version: '3'

services:
  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    volumes:
      - /var/lib/nextcloud/app:/var/www/html
    ports:
      - 8084:80
    links:
      - db
    environment:
      - NEXTCLOUD_ADMIN_USER=
      - NEXTCLOUD_ADMIN_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db

    env_file:
      - .env

  db:
    container_name: nextcloud_mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /var/lib/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  db: